import pytest

from sf6_ranking.client import Client


@pytest.fixture
def client(scope="function"):
    return Client()


@pytest.fixture
def master_ranking_data(scope="module"):
    return {
        "pageProps": {
            "master_rating_ranking": {
                "current_page": 1,
                "my_ranking_info": {
                    "character_id": 17,
                    "fighter_banner_info": {
                        "allow_cross_play": True,
                        "battle_input_type": 0,
                        "custom_room_invite_setting": 1,
                        "enjoy_total_point": 3554,
                        "favorite_character_id": 17,
                        "favorite_character_league_info": {
                            "league_point": 60556,
                            "league_rank": 36,
                            "master_league": 36,
                            "master_rating": 1328,
                            "master_rating_ranking": 190999,
                        },
                        "favorite_character_play_point": {
                            "battle_hub": 36935,
                            "fighting_ground": 132113,
                            "world_tour": 5508,
                        },
                        "friend_request_flag": False,
                        "friendship": 1,
                        "home_id": 61,
                        "inside_rank": 2,
                        "is_circle_invite": True,
                        "is_circle_member": False,
                        "last_play_at": 1732919476,
                        "main_circle": {
                            "circle_id": "1ca7b2751082409ca118ec29969e5741",
                            "circle_name": "CircleTest",
                            "data_exist": True,
                            "emblem": {
                                "emblem_base": 8,
                                "emblem_base_color": 2,
                                "emblem_frame": 2,
                                "emblem_frame_color": 1,
                                "emblem_pattern": 15,
                                "emblem_pattern_color": 19,
                                "emblem_pattern_horizontal_inversion": False,
                                "emblem_pattern_vertical_inversion": False,
                                "emblem_processing": 1,
                                "emblem_symbol1": 40023,
                                "emblem_symbol1_clipping": True,
                                "emblem_symbol1_color": 5,
                                "emblem_symbol1_horizontal_inversion": False,
                                "emblem_symbol1_vertical_inversion": False,
                                "emblem_symbol2": 40001,
                                "emblem_symbol2_clipping": False,
                                "emblem_symbol2_color": 1,
                                "emblem_symbol2_horizontal_inversion": False,
                                "emblem_symbol2_vertical_inversion": False,
                            },
                            "leader": {
                                "fighter_id": "User Test",
                                "platform_id": 5,
                                "short_id": 32332977363,
                            },
                        },
                        "max_content_play_time": {
                            "content_type": 2,
                            "play_time": 431449,
                        },
                        "mobile_linkage": False,
                        "online_status_info": {
                            "battlehub_admission_restriction": 0,
                            "battlehub_id": "",
                            "battlehub_platform_id": 0,
                            "battlehub_region_id": 0,
                            "battlehub_server_no": 0,
                            "custom_room_master_short_id": 0,
                            "custom_room_platform_id": 0,
                            "custom_room_publish_setting": 1,
                            "custom_room_region_id": 0,
                            "custom_room_required_network_connection_quality": 0,
                            "custom_room_required_pass_code": False,
                            "custom_room_room_id": "",
                            "online_status": 1,
                        },
                        "personal_info": {
                            "fighter_id": "User Test",
                            "platform_id": 5,
                            "short_id": 32332977363,
                            "platform_name": "Steam",
                            "platform_tool_name": "steam",
                        },
                        "play_time_zone": {
                            "end_hour": 22,
                            "end_minute": 0,
                            "start_hour": 21,
                            "start_minute": 30,
                        },
                        "profile_comment": {"profile_tag_id": 1, "tag_option_id": 0},
                        "title_plate": 10917,
                        "favorite_character_name": "Marisa",
                        "favorite_character_tool_name": "marisa",
                        "title_data": {
                            "title_data_id": 10917,
                            "title_data_grade_id": 2,
                            "title_data_grade_name": "銀",
                            "title_data_plate_id": 323,
                            "title_data_plate_name": "323-e309712adacc29fa96704b79ae30a6",
                            "title_data_val": "Stupéfiant mort-vivant",
                        },
                        "home_name": "France",
                    },
                    "league_point": 60556,
                    "league_rank": 36,
                    "master_league": 36,
                    "master_rating_ranking": 190999,
                    "order": 190734,
                    "ranking_title_plate": 10917,
                    "rating": 1328,
                    "character_name": "Marisa",
                    "character_tool_name": "marisa",
                    "ranking_title_data": {
                        "title_data_id": 10917,
                        "title_data_grade_id": 2,
                        "title_data_grade_name": "銀",
                        "title_data_plate_id": 323,
                        "title_data_plate_name": "323-e309712adacc29fa96704b79ae30a6",
                        "title_data_val": "Stupéfiant mort-vivant",
                    },
                },
                "ranking_fighter_list": [
                    {
                        "character_id": 14,
                        "fighter_banner_info": {
                            "allow_cross_play": True,
                            "battle_input_type": 0,
                            "custom_room_invite_setting": 1,
                            "enjoy_total_point": 4333,
                            "favorite_character_id": 14,
                            "favorite_character_league_info": {
                                "league_point": 503333,
                                "league_rank": 36,
                                "master_league": 37,
                                "master_rating": 2234,
                                "master_rating_ranking": 1,
                            },
                            "favorite_character_play_point": {
                                "battle_hub": 2173,
                                "fighting_ground": 626543,
                                "world_tour": 1360,
                            },
                            "friend_request_flag": False,
                            "friendship": 2,
                            "home_id": 85,
                            "inside_rank": 2,
                            "is_circle_invite": True,
                            "is_circle_member": False,
                            "last_play_at": 1732894496,
                            "main_circle": {
                                "circle_id": "5584362f0b084505bf66f754c578c4d0",
                                "circle_name": "TAKAGIdojo",
                                "data_exist": True,
                                "emblem": {
                                    "emblem_base": 12,
                                    "emblem_base_color": 1,
                                    "emblem_frame": 1,
                                    "emblem_frame_color": 8,
                                    "emblem_pattern": 3,
                                    "emblem_pattern_color": 1,
                                    "emblem_pattern_horizontal_inversion": False,
                                    "emblem_pattern_vertical_inversion": False,
                                    "emblem_processing": 1,
                                    "emblem_symbol1": 40163,
                                    "emblem_symbol1_clipping": False,
                                    "emblem_symbol1_color": 5,
                                    "emblem_symbol1_horizontal_inversion": False,
                                    "emblem_symbol1_vertical_inversion": False,
                                    "emblem_symbol2": 40098,
                                    "emblem_symbol2_clipping": False,
                                    "emblem_symbol2_color": 13,
                                    "emblem_symbol2_horizontal_inversion": False,
                                    "emblem_symbol2_vertical_inversion": False,
                                },
                                "leader": {
                                    "fighter_id": "ラボモンスター高木",
                                    "platform_id": 5,
                                    "short_id": 3249813921,
                                },
                            },
                            "max_content_play_time": {
                                "content_type": 2,
                                "play_time": 4052836,
                            },
                            "mobile_linkage": False,
                            "online_status_info": {
                                "battlehub_admission_restriction": 0,
                                "battlehub_id": "",
                                "battlehub_platform_id": 0,
                                "battlehub_region_id": 0,
                                "battlehub_server_no": 0,
                                "custom_room_master_short_id": 0,
                                "custom_room_platform_id": 0,
                                "custom_room_publish_setting": 1,
                                "custom_room_region_id": 0,
                                "custom_room_required_network_connection_quality": 0,
                                "custom_room_required_pass_code": False,
                                "custom_room_room_id": "",
                                "online_status": 1,
                            },
                            "personal_info": {
                                "fighter_id": "satoru_pc",
                                "platform_id": 5,
                                "short_id": 1732856596,
                                "platform_name": "Steam",
                                "platform_tool_name": "steam",
                            },
                            "play_time_zone": {
                                "end_hour": 13,
                                "end_minute": 30,
                                "start_hour": 12,
                                "start_minute": 30,
                            },
                            "profile_comment": {
                                "profile_tag_id": 7,
                                "tag_option_id": 0,
                            },
                            "title_plate": 10824,
                            "favorite_character_name": "Rashid",
                            "favorite_character_tool_name": "rashid",
                            "title_data": {
                                "title_data_id": 10824,
                                "title_data_grade_id": 5,
                                "title_data_grade_name": "グレード5",
                                "title_data_plate_id": 252,
                                "title_data_plate_name": "252-99e03c8ee4b5e7bae44d8378ba38fb",
                                "title_data_val": "Légende de la phase 5",
                            },
                            "home_name": "Japon",
                        },
                        "league_point": 0,
                        "league_rank": 36,
                        "master_league": 37,
                        "master_rating_ranking": 1,
                        "order": 1,
                        "ranking_title_plate": 10824,
                        "rating": 2234,
                        "character_name": "Rashid",
                        "character_tool_name": "rashid",
                        "ranking_title_data": {
                            "title_data_id": 10824,
                            "title_data_grade_id": 5,
                            "title_data_grade_name": "グレード5",
                            "title_data_plate_id": 252,
                            "title_data_plate_name": "252-99e03c8ee4b5e7bae44d8378ba38fb",
                            "title_data_val": "Légende de la phase 5",
                        },
                    },
                    {
                        "character_id": 9,
                        "fighter_banner_info": {
                            "allow_cross_play": True,
                            "battle_input_type": 0,
                            "custom_room_invite_setting": 1,
                            "enjoy_total_point": 3368,
                            "favorite_character_id": 9,
                            "favorite_character_league_info": {
                                "league_point": 461375,
                                "league_rank": 36,
                                "master_league": 37,
                                "master_rating": 2231,
                                "master_rating_ranking": 2,
                            },
                            "favorite_character_play_point": {
                                "battle_hub": 580,
                                "fighting_ground": 240782,
                                "world_tour": 0,
                            },
                            "friend_request_flag": False,
                            "friendship": 2,
                            "home_id": 85,
                            "inside_rank": 2,
                            "is_circle_invite": True,
                            "is_circle_member": False,
                            "last_play_at": 1732881639,
                            "main_circle": {
                                "circle_id": "d360e6c156d04b468552ac8fd0c00b3b",
                                "circle_name": "MIZUCLUB",
                                "data_exist": True,
                                "emblem": {
                                    "emblem_base": 6,
                                    "emblem_base_color": 1,
                                    "emblem_frame": 2,
                                    "emblem_frame_color": 3,
                                    "emblem_pattern": 1,
                                    "emblem_pattern_color": 1,
                                    "emblem_pattern_horizontal_inversion": False,
                                    "emblem_pattern_vertical_inversion": False,
                                    "emblem_processing": 35002,
                                    "emblem_symbol1": 40078,
                                    "emblem_symbol1_clipping": False,
                                    "emblem_symbol1_color": 1,
                                    "emblem_symbol1_horizontal_inversion": False,
                                    "emblem_symbol1_vertical_inversion": False,
                                    "emblem_symbol2": 40118,
                                    "emblem_symbol2_clipping": False,
                                    "emblem_symbol2_color": 4,
                                    "emblem_symbol2_horizontal_inversion": False,
                                    "emblem_symbol2_vertical_inversion": False,
                                },
                                "leader": {
                                    "fighter_id": "Mizuha",
                                    "platform_id": 5,
                                    "short_id": 1617165084,
                                },
                            },
                            "max_content_play_time": {
                                "content_type": 8,
                                "play_time": 2210098,
                            },
                            "mobile_linkage": False,
                            "online_status_info": {
                                "battlehub_admission_restriction": 0,
                                "battlehub_id": "",
                                "battlehub_platform_id": 0,
                                "battlehub_region_id": 0,
                                "battlehub_server_no": 0,
                                "custom_room_master_short_id": 0,
                                "custom_room_platform_id": 0,
                                "custom_room_publish_setting": 1,
                                "custom_room_region_id": 0,
                                "custom_room_required_network_connection_quality": 0,
                                "custom_room_required_pass_code": False,
                                "custom_room_room_id": "",
                                "online_status": 1,
                            },
                            "personal_info": {
                                "fighter_id": "Mizuha",
                                "platform_id": 5,
                                "short_id": 1617165084,
                                "platform_name": "Steam",
                                "platform_tool_name": "steam",
                            },
                            "play_time_zone": {
                                "end_hour": 11,
                                "end_minute": 0,
                                "start_hour": 9,
                                "start_minute": 30,
                            },
                            "profile_comment": {
                                "profile_tag_id": 1,
                                "tag_option_id": 0,
                            },
                            "title_plate": 10570,
                            "favorite_character_name": "Cammy",
                            "favorite_character_tool_name": "cammy",
                            "title_data": {
                                "title_data_id": 10570,
                                "title_data_grade_id": 3,
                                "title_data_grade_name": "金",
                                "title_data_plate_id": 63,
                                "title_data_plate_name": "63-fc401cde3cb655e17f26493449c0bd",
                                "title_data_val": "Je t'aime beaucoup",
                            },
                            "home_name": "Japon",
                        },
                        "league_point": 0,
                        "league_rank": 36,
                        "master_league": 37,
                        "master_rating_ranking": 2,
                        "order": 2,
                        "ranking_title_plate": 10570,
                        "rating": 2231,
                        "character_name": "Cammy",
                        "character_tool_name": "cammy",
                        "ranking_title_data": {
                            "title_data_id": 10570,
                            "title_data_grade_id": 3,
                            "title_data_grade_name": "金",
                            "title_data_plate_id": 63,
                            "title_data_plate_name": "63-fc401cde3cb655e17f26493449c0bd",
                            "title_data_val": "Je t'aime beaucoup",
                        },
                    },
                ],
                "total_count": 202498,
                "total_page": 10125,
            },
        },
    }
